application: hb-bookmarks
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: "14d"

- url: /tasks/.*
  script: app.py
  login: admin

- url: /.*
  script: app.py

builtins:
- datastore_admin: on
- appstats: on
- deferred: on
- remote_api: on
